config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "blog_posts#index"
  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :email, uniqueness: true, presence: true

    default_scope { order(arel_table["published_at"].desc.nulls_last) }
    #default_scope { order(Arel.sql("published_at DESC NULLS LAST")) }
    scope :draft, -> { where(published_at: nil) }
    scope :scheduled, -> { where("published_at > ?", Time.now) }
    scope :published, -> { where("published_at <= ?", Time.now) }

    mount_uploader :image, ImageUploader 
    has_one_attached :cover do |attachable|
      attachable.variant :thumb, resize_to_limit: [100, 100]
    end

    def published_at_string
        published_at&.to_formatted_s(:long)
    end

    def draft?
        published_at.nil?
    end

    def scheduled?
      published_at? && published_at > Time.now
    end

    def published?
      published_at? && published_at <= Time.now
    end

    def state
      return :draft if draft?
      return :scheduled if scheduled?
      return :published if published?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController 
    before_action :authenticate_user!, except: [:index, :show]
    before_action :fetch_post, only: [:show, :edit, :update, :destroy]

    def index
      @blog_posts = user_signed_in? ? BlogPost.all : BlogPost.published
    end

    def show
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
      @blog_post = BlogPost.new(post_params)
      if (@blog_post.save) 
        redirect_to blog_posts_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @blog_post.update(post_params) 
        redirect_to @blog_post
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
     @blog_post.destroy
     redirect_to root_path 
    end

    private
    def fetch_post
      @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Post not found!"
      redirect_to root_path
    end

    def post_params 
      params.require(:blog_post).permit(:title, :body, :email, :published_at, :image, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
<h1>Edit post</h1>
<%= render partial: 'partial/form',  locals: {blog_post: @blog_post} %>

app/views/blog_posts/index.html.erb
<h1>Blog</h1>
<% if user_signed_in? %>
    <%= link_to current_user.email, edit_user_registration_path %>
    <%= link_to "sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
    <%= link_to "sign in", new_user_session_path %>
    <%= link_to "sign up", new_user_registration_path %>
<% end %>
<% @blog_posts.each do |post| %>
    <h3><%= link_to post.title, post %> - 
    <% if user_signed_in? %>
        <%= button_to "Delete", post, method: :delete, data: { turbo_confirm: "Are you sure?"} %></h3>
    <% end %>
    <p><%= post.body %> - <%= post.state %></p>
<% end %>
<% if user_signed_in? %>
    <%= link_to "Create new", new_blog_post_path %> 
<% end %>

app/views/blog_posts/new.html.erb
<h1>Create new post</h1>

<%= render partial: "partial/form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>
<% if @blog_post.image.present? %>
  <%= image_tag(@blog_post.image.url(:thumb)) %>
<% end %>
<% if @blog_post.cover.present? %>
  <%= image_tag @blog_post.cover.variant(:thumb) %>
<% end %>
<%= link_to "Edit", edit_blog_post_path(@blog_post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'partial/alerts' %>

    <%= yield %>

    <div><%= link_to "Home", root_path %></div>
  </body>
</html>

app/views/partial/_alerts.html.erb
<% flash.each do |type, msg| %>
    <div><%= msg %></div>
<% end %>

app/views/partial/_form.html.erb
<%= form_with model: blog_post do |form| %>
  <ul>
  <% form.object.errors.each do |error| %>
    <li><%= error.full_message %></li>
  <% end %>
  </ul>
  <div>
    <%= form.text_field :title, placeholder: "post title" %>
  </div>
  <div>
    <%= form.text_area :body, placeholder: "post body" %>
  </div>
  <div>
    <%= form.text_area :email, placeholder: "email" %>
  </div>
  <div>
    <%= form.datetime_select :published_at %>
  </div>
  <div>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.file_field :cover %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>